spring:
  application:
    name: fellow-gigachat
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/chat}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
